-- Temporary RLS Disable for Testing
-- ONLY USE THIS FOR DEVELOPMENT/TESTING
-- Run this in Supabase SQL Editor if you need to test without RLS

-- Disable RLS temporarily (for testing only)
ALTER TABLE IF EXISTS chat_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS whiteboards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS folders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS n8n_connections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mcp_servers DISABLE ROW LEVEL SECURITY;

-- Note: Remember to re-enable RLS and set up proper policies for production! 