export { ProjectProgressWidget } from './ProjectProgressWidget';
export { AgentStatusWidget } from './AgentStatusWidget';
export { QuickActionsWidget } from './QuickActionsWidget';
export { PendingTasksWidget } from './PendingTasksWidget';
export { WidgetErrorBoundary } from './WidgetErrorBoundary';
export { WidgetSkeleton } from './WidgetSkeleton';
export { FocusEventsWidget } from './FocusEventsWidget';
export { MailWidget } from './MailWidget';
export { RecentActivityWidget } from './RecentActivityWidget';
